### ISSUE TITLE
Status of Project

### ISSUE THREAD

**Issue by airarrazaval** [formio/api#13]
Hi, just wondering if this project is still being developed or if it has been replaced by other project.

**Comment by travist** [comment]
This project was developed as a prototype for our "next gen" server. However, through a couple of iterations, we have started using the [Nest.js Framework](https://nestjs.com) and are currently experimenting using that framework as the core. That effort is proving to be more robust, so it looks like we may be moving in that direction and ultimately this library will be completely refactored within that framework. More coming soon.
